# Generated by Django 4.0.3 on 2022-04-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
