# Generated by Django 4.0.3 on 2022-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.CharField(max_length=1000),
        ),
    ]
