# Generated by Django 4.1.2 on 2022-10-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_quiz_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='username',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='attempts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
